### ISSUE TITLE
Plans to move the plugin to the main QGIS repository?

### ISSUE THREAD

**Issue by newcomb-d** [alexbruy/processing-wbt#39]
Are there plans to move this tool to the main QGIS repository?

**Comment by jblindsay** [comment]
I enquired about this myself on the QGIS developer mail list and there was no love for the idea I'm afraid. I was informed afterwards that QGIS is no longer looking to incorporate standard toolbox plugins. I'm sure that if the community were vocal enough about the desire to include WBT, they might reconsider the position though.

**Comment by alexbruy** [comment]
> Are there plans to move this tool to the main QGIS repository?

I see no point in this.

**Comment by wonder-sk** [comment]
hello @jblindsay - a QGIS developer here...

Maybe a misunderstanding, but there are two distinct things regarding QGIS plugins:
- option A - have a plugin listed in the official QGIS plugin repository, available for users to install through the plugin installer (https://plugins.qgis.org/plugins/)
- option B - have a plugin integrated directly into QGIS source code git repository (https://github.com/qgis/QGIS/)

I don't think there's any opposition to have "option A" - I am sure having an easy way to add WBT to Processing toolbox would be very appreciated by QGIS users. I am not sure what was the main motivation of Alex to host WBT plugin in a 3rd party plugin repository, but developers are generally encouraged to upload their plugins to the official plugin repository.

As for "option B", adding _any_ new plugins to QGIS source code is generally discouraged. The reason is mainly to lower maintenance burden of core QGIS developers and to improve user experience (if some functionality is in QGIS code, it should be integrated properly, not "just" a plugin). And especially for Processing providers the situation was getting confusing for users when there were several GIS libraries supported out of the box, and users would get presented with 5 variants of the same algorithm, just coming from different providers (SAGA, GRASS, Orfeo, Lastools, ...)

So I would encourage you to go for the "option A" - adding WBT plugin to the official QGIS plugin repo should be a matter of few minutes :-) Best if Alex as the author would do that (assuming he's happy to have the plugin in the official plugin repository?)

**Comment by jblindsay** [comment]
@wonder-sk Hello Martin and thank you kindly for clarifying this point. I would be very interested in having the WBT plugin listed in the QGIS plugin repository and will certainly pursue this further. I will have to discuss this further with Alex and see his thoughts on this as well.
