### ISSUE TITLE
Installing the QGIS plugin

### ISSUE THREAD

**Issue by momeni133** [alexbruy/processing-wbt#43]
Hello,
I am trying to add the Whitebox plugin into my QGIS (v. 3.20).
After installing the plugin, inside the "Settings/Options/Providers/WhiteboxTools" There is no checkbox to select.
![image](https://user-images.githubusercontent.com/33343341/122661944-5600f880-d15d-11eb-8c3b-f5905c7dabed.png).
I am using Linux Mint 20.1.

Thanks,

**Comment by alexbruy** [comment]
Is this a bug report or a question? I don't see anything wrong here.

**Comment by cefect** [comment]
There should be three dots that let you specify the location of the executable

![image](https://user-images.githubusercontent.com/47092034/125879488-f434a375-1295-4e0e-9f20-cd7146d3f2a2.png)

**Comment by dflaim** [comment]
> 
> 
![Plugin issue](https://user-images.githubusercontent.com/87590065/126053730-d08d5ff1-b504-461a-b704-bc45ef6c8ba2.GIF)

> There should be three dots that let you specify the location of the executable
> 
> ![image](https://user-images.githubusercontent.com/47092034/125879488-f434a375-1295-4e0e-9f20-cd7146d3f2a2.png)
Thanks Alex for the plugin - I'm looking forward to using it.
I'm having the same issue using Qgis 3.20.0 on Windows.  The tools won't work since there is no option to specify a path to the executable or activate the plugin (as there is on the LAStools plugin on this image).
